import credentials
import argparse
from helper.text_cleaner import clean
from helper.text_clean import clean_link
from api_handlers.youtube import Youtube
from api_handlers.spotify import Spotify

parser = argparse.ArgumentParser(description='Convert your Youtube playlist to a Spotify playlist')
parser.add_argument('-yt', '--Youtube', default='PL7q6nAW6-CMsgIpYt9hwRycy6lShNf6wP', metavar='', help='Youtube Playlist Link')
parser.add_argument('-su', '--SpotifyUName', default='ogtihcg7j5wxoo9fkfsqjffwl', metavar='', help='Your Spotify Username')
parser.add_argument('-sc', '--SpotifyClient', default='c9ff8e6e4d144e4dad0be65db061783f', metavar='', help='Your Spotify Client Code')
parser.add_argument('-ss', '--SpotifySecret', default='764f819bbd0d488e990739eb279a0b4f', metavar='', help='Your Spotify Secret Code')
parser.add_argument('-name', '--PlaylistName', default='Autogenerated', metavar='', help="Generated playlist's name")
args = parser.parse_args()

youtube = Youtube(credentials.youtube_key)
spotify = Spotify(args.SpotifyUName, args.SpotifyClient, args.SpotifySecret)

songs_list = youtube.fetch(clean_link(args.Youtube)) #'PL7q6nAW6-CMsgIpYt9hwRycy6lShNf6wP'
spotify.generate(playlist_name=args.PlaylistName, songs_list=songs_list)
print("DONE!")
