import credentials
import argparse
from helper.text_cleaner import clean
from helper.text_clean import clean_link
from api_handlers.youtube import Youtube
from api_handlers.spotify import Spotify

parser = argparse.ArgumentParser(description='Convert your Youtube playlist to a Spotify playlist')
parser.add_argument('-yt', '--Youtube', metavar='', help='Youtube Playlist Link')
parser.add_argument('-su', '--SpotifyUName', metavar='', help='Your Spotify Username')
parser.add_argument('-sc', '--SpotifyClient', metavar='', help='Your Spotify Client Code')
parser.add_argument('-ss', '--SpotifySecret', metavar='', help='Your Spotify Secret Code')
parser.add_argument('-name', '--PlaylistName', default='Autogenerated', metavar='', help="Generated playlist's name")
args = parser.parse_args()

youtube = Youtube(credentials.youtube_key)
spotify = Spotify(args.SpotifyUName, args.SpotifyClient, args.SpotifySecret)

songs_list = youtube.fetch(clean_link(args.Youtube))
spotify.generate(playlist_name=args.PlaylistName, songs_list=songs_list)
print("DONE!")
